contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #concordance channel"
    url: https://nfcore.slack.com/channels/concordance
    about: Discussion about the nf-core/concordance pipeline
